services:
  musicbot:
    build: .
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    volumes:
      - ./config:/musicbot/config/
      - ./audio_cache:/musicbot/audio_cache
      - ./data:/musicbot/data
      - ./logs:/musicbot/logs
